name = "SimpleLJ_MD"
uuid = "71718ea6-e477-4789-99d7-46775e745a35"
authors = ["viniciuspiccoli <viniciuspiccoli2008@hotmail.com> and contributors"]
version = "1.0.1-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
